### PR TITLE
solved a error

### PR DESCRIPTION
**Pull request by mugund10**
##i found a small error while learning the course on the topic metadata.

the function metadata.FromIncomingContext(ctx) always returns the bool value as true so i change it with another conditional  statement and its works

### CODE REVIEW

**Comment by tebeka** [comment]
Thanks! I don't see that it always returns true. I've tried the following and it returned `false`:

```go
package main

import (
	"context"
	"fmt"

	"google.golang.org/grpc/metadata"
)

func main() {
	md, ok := metadata.FromIncomingContext(context.Background())
	fmt.Println(ok)                       // false
	fmt.Println(md.Get("api-key") == nil) // true

}
```

Also if you call `md.Get`, you will get nil.

**Comment by mugund10** [comment]
ohh sorry sir, actually its my keyboard problem , i mistyped it { md.Get("apikey") }, yes i missed the under score .

try with this   >> md.Get("api_key"),

mybad

**Comment by tebeka** [comment]
> try with this >> md.Get("api_key"),

How is this different than my example? You'd still get `nil`

**Comment by mugund10** [comment]
sir i hope this helps
server
client

**Pull request closed without merging**
